# Generated by Django 3.0.7 on 2020-10-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='codebase_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_project_link',
            field=models.URLField(),
        ),
    ]
