# Generated by Django 3.0.7 on 2020-10-24 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20201020_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='code_goal',
            field=models.TextField(verbose_name='your coding goal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(help_text='Enter your active email address', max_length=50, verbose_name='your email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.CharField(max_length=200, verbose_name='your interests'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='your phone number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
