# Generated by Django 3.0.7 on 2020-10-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201020_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
